import streamlit as st
import pandas as pd
import joblib
import shap
import sqlite3
import matplotlib.pyplot as plt

from reportlab.platypus import SimpleDocTemplate, Paragraph, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4

# ---------------- CONFIG ----------------
st.set_page_config(page_title="Industrial Credit Risk System", layout="wide")

# ---------------- LOAD MODEL ----------------
model = joblib.load("credit_model.pkl")

# ---------------- LOAD DATA ----------------
df = pd.read_csv("Loan_default.csv")
if "LoanID" in df.columns:
    df = df.drop(columns=["LoanID"])

feature_cols = df.drop(columns=["Default"]).columns

# ---------------- DATABASE ----------------
conn = sqlite3.connect("credit_history.db", check_same_thread=False)
cur = conn.cursor()

cur.execute("""
CREATE TABLE IF NOT EXISTS history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    probability REAL,
    cibil INTEGER,
    decision TEXT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
)
""")
conn.commit()

# ---------------- UTILS ----------------
def calculate_cibil(prob):
    score = int(900 - (prob * 600))
    return max(300, min(score, 900))

def decision_from_score(score):
    if score >= 750:
        return "LOW RISK – APPROVED"
    elif score >= 650:
        return "MEDIUM RISK – HIGH INTEREST"
    elif score >= 550:
        return "HIGH RISK – LOW LIMIT"
    else:
        return "VERY HIGH RISK – REJECTED"

# ---------------- PDF ----------------
def generate_pdf(name, prob, cibil, decision):
    file_name = f"{name}_credit_report.pdf"
    pdf = SimpleDocTemplate(file_name, pagesize=A4)
    styles = getSampleStyleSheet()

    content = [
        Image("bank_logo.png", width=120, height=60),
        Paragraph("<b>CREDIT RISK ASSESSMENT REPORT</b>", styles["Title"]),
        Paragraph(f"Applicant Name: {name}", styles["Normal"]),
        Paragraph(f"Default Probability: {round(prob, 3)}", styles["Normal"]),
        Paragraph(f"CIBIL Score: {cibil}", styles["Normal"]),
        Paragraph(f"Final Decision: <b>{decision}</b>", styles["Normal"]),
        Paragraph("Generated by Industrial Credit Risk System", styles["Italic"])
    ]

    pdf.build(content)
    return file_name

# ---------------- UI ----------------
st.title("🏦 Industrial Credit Risk Assessment System")
st.caption("Pipeline ML • Bank Policy Rules • SHAP Explainability")

name = st.text_input("Applicant Name")

input_data = {}

st.markdown("---")
st.subheader("👤 Personal Details")

for col in feature_cols:
    if col.lower() == "age":
        input_data[col] = st.number_input(
            "Age (Years)",
            min_value=18,
            max_value=100,
            step=1,
            value=30
        )

st.markdown("---")
st.subheader("💰 Loan Details")

for col in feature_cols:
    col_l = col.lower()
    if "loan" in col_l and "amount" in col_l:
        input_data[col] = st.number_input(
            "Loan Amount (in Lakhs)",
            min_value=0.0,
            step=0.1,
            value=5.0
        )
    elif "interest" in col_l:
        input_data[col] = st.number_input(
            "Interest Rate (% p.a.)",
            min_value=0.0,
            step=0.1,
            value=10.0
        )
    elif "tenure" in col_l:
        input_data[col] = st.number_input(
            "Loan Tenure (Years)",
            min_value=1,
            max_value=40,
            step=1,
            value=5
        )

st.markdown("---")
st.subheader("🧾 Credit & Employment Details")

for col in feature_cols:
    if col not in input_data:
        if df[col].dtype == "object":
            input_data[col] = st.selectbox(
                col.replace("_", " "),
                sorted(df[col].dropna().unique())
            )
        else:
            input_data[col] = st.number_input(
                col.replace("_", " "),
                step=1,
                value=0
            )

# ---------------- ASSESS ----------------
if st.button("🔍 Assess Credit Risk"):

    # Create input dataframe
    input_df = pd.DataFrame([input_data])

    # 1️⃣ ML Prediction
    prob = model.predict_proba(input_df)[0][1]

    # 2️⃣ Convert to CIBIL
    cibil = calculate_cibil(prob)

    # 3️⃣ Read key inputs safely
    credit_score = input_data.get("CreditScore", 999)
    income = input_data.get("Income", 999)        # income in lakhs
    past_defaults = input_data.get("PastDefaults", 0)

    # 4️⃣ BANK POLICY OVERRIDES
    if credit_score < 500:
        decision = "VERY HIGH RISK – REJECTED (Low Credit Score)"
    elif income < 2:
        decision = "VERY HIGH RISK – REJECTED (Low Income)"
    elif past_defaults >= 2:
        decision = "VERY HIGH RISK – REJECTED (Multiple Past Defaults)"
    else:
        decision = decision_from_score(cibil)

    # Save history
    cur.execute(
        "INSERT INTO history (name, probability, cibil, decision) VALUES (?, ?, ?, ?)",
        (name, prob, cibil, decision)
    )
    conn.commit()

    st.markdown("---")
    st.subheader("📊 Credit Assessment Result")

    c1, c2, c3 = st.columns(3)
    c1.metric("Default Probability", round(prob, 3))
    c2.metric("CIBIL Score", cibil)
    c3.success(decision)

    st.markdown("---")
    st.subheader("🧠 Model Explainability (SHAP)")

    #before
   
    # after
    # background dataset (small sample for speed)
    background = model.named_steps["preprocessor"].transform(df.drop(columns=["Default"]).sample(50))

    # prediction function
    def predict_fn(x):
        return model.named_steps["model"].predict_proba(x)[:,1]

    # transform input
    X_transformed = model.named_steps["preprocessor"].transform(input_df)

    # safe explainer
    explainer = shap.Explainer(predict_fn, background)

    # shap values
    shap_values = explainer(X_transformed)

    # plot
    fig, ax = plt.subplots(figsize=(4,3))
    shap.waterfall_plot(
        shap.Explanation(
            values=shap_values[0].values,
            base_values=shap_values[0].base_values,
            feature_names=model.named_steps["preprocessor"].get_feature_names_out()
        ),
        show=False
    )


    st.pyplot(fig)




    
    st.markdown("---")
    pdf_file = generate_pdf(name, prob, cibil, decision)
    with open(pdf_file, "rb") as f:
        st.download_button("📄 Download Credit Report", f, file_name=pdf_file)

# ---------------- HISTORY ----------------
st.markdown("---")
st.subheader("🗂 Assessment History")
history = pd.read_sql("SELECT * FROM history ORDER BY timestamp DESC", conn)
st.dataframe(history)
